# Generated by Django 3.2 on 2022-09-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_1', models.CharField(max_length=25)),
                ('status_2', models.CharField(max_length=25)),
                ('dt_ts', models.DateTimeField()),
            ],
        ),
    ]
