# Generated by Django 3.2 on 2022-09-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_1', models.CharField(max_length=25)),
                ('status_2', models.CharField(max_length=25)),
                ('dt_ts', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
