# Generated by Django 3.2 on 2022-09-26 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_machines_dt_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='dt_ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 23, 40, 33, 152460)),
        ),
    ]
