# Generated by Django 3.2 on 2022-09-26 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_machines_dt_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='dt_ts',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 0, 33, 2, 587477)),
        ),
    ]
